version: '3.4'

services:
  ats-nginx:
    image: nginx:latest
    container_name: ats-nginx
    restart: unless-stopped
    ports:
      - 5443:443
    environment:
      - EXPOSE_DEV_ENDPOINTS=1
    volumes:
      - ../configs/nginx/ssl:/ssl/
      - ../configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../configs/nginx/mime.types:/etc/nginx/mime.types
      - ../logs:/logs/
    depends_on:
      - ats-backend
      - ats-frontend

    deploy:
      replicas: ${ATS_NGINX_REPLICAS:-1}


  ats-frontend:
    container_name: ats-frontend
    build:
      context: ..
      dockerfile: ./docker/frontend.Dockerfile
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ..:/app
      - /app/src/frontend/node_modules
    deploy:
      replicas: ${ATS_FRONTEND_REPLICAS:-1}

  ats-backend:
    container_name: ats-backend
    build:
      context: ..
      dockerfile: ./docker/backend.Dockerfile
      target: prod
    restart: always
    ports:
      - 8000:8000
      - 5689:5678
    stdin_open: true
    tty: true
    volumes:
      - ..:/app

    deploy:
      replicas: ${ATS_BACKEND_REPLICAS:-1}



networks:
  default:


