data_folder: "data"
resume_extension: ".docx"

llm:
  provider: ${GROQ_PROVIDER}
  model_name: ${GROQ_MODEL_NAME}
  endpoint: ${GROQ_ENDPOINT}
  api_key: ${GROQ_API_KEY}
  temperature: 0.0
  max_tokens: 4096