data_folder: "data"
resume_extension: ".docx"

llm:
  provider: "groq"
  model_name: "gemma2-9b-it"
  endpoint: "https://api.groq.com/openai/v1/chat/completions"
  api_key: "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"
  temperature: 0.0
  max_tokens: 4096